name: 'Create Debian Repository'
description: 'Create full debian repository metadata on disk, ready to be served'
inputs:
  github_token:
    default: ${{ github.token }}
  source:
    default: ${{ github.repository }}
  archs:
    default: 'i386 amd64 armhf arm64 mips64el ppc64el riscv64 s390x'
  mode:
    default: write
  directory:
    default: .
runs:
  using: composite
  steps:
    - shell: bash
      working-directory: ${{ inputs.directory }}
      run: mkdir -p pool/main
    - shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      working-directory: ${{ inputs.directory }}
      run: |
        cd pool/main
        cat <<< "${{ inputs.source }}" | tr ',' '\n' | tr ';' '\n' | tr ' ' '\n' | xargs -I '{}' gh api /repos/'{}'/releases --paginate | jq '.[] | .assets[] | select(.name | endswith(".deb")) | .url' -c --unbuffered | xargs -r wget --header "Authorization: Bearer $GH_TOKEN" --header 'Accept: application/octet-stream' --tries inf --random-wait -nc
        ls | while read -r file; do mv "$file" "$file".deb; done
    - shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        cat <<< "${{ inputs.archs }}" | tr ',' '\n' | tr ';' '\n' | tr ' ' '\n' | while read -r arch; do
          mkdir -p dists/stable/main/binary-"$arch"
          [ ${{ inputs.mode }} = append ] || rm -rf dists/stable/main/binary-"$arch"/Packages
          dpkg-scanpackages --arch "$arch" pool/main >> dists/stable/main/binary-"$arch"/Packages
          gzip -9 < dists/stable/main/binary-"$arch"/Packages > dists/stable/main/binary-"$arch"/Packages.gz
        done
    - shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        cd dists/stable
        {
          do_hash() {
              HASH_NAME=$1
              HASH_CMD=$2
              echo "${HASH_NAME}:"
              for f in $(find -type f); do
                  f=$(echo $f | cut -c3-) # remove ./ prefix
                  if [ "$f" = "Release" ]; then
                      continue
                  fi
                  echo " $(${HASH_CMD} ${f}  | cut -d" " -f1) $(wc -c $f)"
              done
          }
          cat << EOF
        Origin: GitHub ${{ github.repository_owner }}
        Label: ${{ github.repository_owner }}
        Suite: stable
        Codename: stable
        Version: 1.0
        Architectures: all
        Components: main
        Description: A software repository hosting packages from github
        Date: $(date -Ru)
        EOF
          do_hash "MD5Sum" "md5sum"
          do_hash "SHA1" "sha1sum"
          do_hash "SHA256" "sha256sum"
        } > Release
