name: 'Create Debian/RPM Repository'
description: 'Create full debian and rpm repository metadata on disk, ready to be served'
inputs:
  github_token:
    default: ${{ github.token }}
  source:
    default: ${{ github.repository }}
  mode:
    default: write
  directory:
    default: .
runs:
  using: composite
  steps:
    - shell: bash
      working-directory: ${{ inputs.directory }}
      run: mkdir -p pool/main
    - shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      working-directory: ${{ inputs.directory }}/pool/main
      run: |
        cat <<< "${{ inputs.source }}" | tr ',' '\n' | tr ';' '\n' | tr ' ' '\n' | xargs -I '{}' gh api /repos/'{}'/releases --paginate | jq '.[] | .assets[] | select(.name | endswith(".deb")) | .url' -r | xargs -r wget --header "Authorization: Bearer $GH_TOKEN" --header 'Accept: application/octet-stream' --tries inf --random-wait -nc 2> /dev/null
    - shell: bash
      working-directory: ${{ inputs.directory }}/pool/main
      run: |
        ls | while read -r file; do
          mv "$file" "$file"_"$(dpkg -I "$file" control | grep 'Architecture:' | cut -d : -f 2 | tr -d ' ')".deb
        done
    - shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        { echo all; dpkg-architecture -L | grep -v -- -; } | while read -r arch; do
          mkdir -p dists/stable/main/binary-"$arch"
          [ ${{ inputs.mode }} = append ] || rm -rf dists/stable/main/binary-"$arch"/Packages
          dpkg-scanpackages --arch "$arch" pool/main >> dists/stable/main/binary-"$arch"/Packages
          if [ "$(wc -c dists/stable/main/binary-"$arch"/Packages)" = 0 ]; then rm -rf dists/stable/main/binary-"$arch"; fi
        done
    - shell: bash
      working-directory: ${{ inputs.directory }}/pool/main
      run: |
        ls | while read -r file; do
          mv "$file" "${file%%_*.deb}"
        done
    - shell: bash
      working-directory: ${{ inputs.directory }}/dists/stable/main
      run: |
        ls | cut -d _ -f 2 | while read -r arch; do 
          sed -i -E 's/([0-9]+)_'"$arch"'\.deb/\1/g' binary_"$arch"/Packages 
        done
    - shell: bash
      working-directory: ${{ inputs.directory }}/dists/stable/main
      run: |
        ls | cut -d _ -f 2 | while read -r arch; do 
          gzip -9 < binary_"$arch"/Packages > "$directory"/Packages.gz
        done
    - shell: bash
      working-directory: ${{ inputs.directory }}/dists/stable
      run: |
        {
          do_hash() {
              HASH_NAME=$1
              HASH_CMD=$2
              echo "${HASH_NAME}:"
              for f in $(find -type f); do
                  f=$(echo $f | cut -c3-) # remove ./ prefix
                  if [ "$f" = "Release" ]; then
                      continue
                  fi
                  echo " $(${HASH_CMD} ${f}  | cut -d" " -f1) $(wc -c $f)"
              done
          }
          cat << EOF
        Origin: GitHub ${{ github.repository_owner }}
        Label: ${{ github.repository_owner }}
        Suite: stable
        Codename: stable
        Version: 1.0
        Architectures: all
        Components: main
        Description: A software repository hosting packages from github
        Date: $(date -Ru)
        EOF
          do_hash "MD5Sum" "md5sum"
          do_hash "SHA1" "sha1sum"
          do_hash "SHA256" "sha256sum"
        } > Release
    - shell: bash
      working-directory: ${{ inputs.directory }}
      run: mkdir -p rpm
    - shell: bash
      env:
        GH_TOKEN: ${{ inputs.github_token }}
      working-directory: ${{ inputs.directory }}/rpm
      run: |
        cat <<< "${{ inputs.source }}" | tr ',' '\n' | tr ';' '\n' | tr ' ' '\n' | xargs -I '{}' gh api /repos/'{}'/releases --paginate | jq '.[] | .assets[] | select(.name | endswith(".rpm")) | .url' -r | xargs -r wget --header "Authorization: Bearer $GH_TOKEN" --header 'Accept: application/octet-stream' --tries inf --random-wait -nc 2> /dev/null
    - shell: bash
      working-directory: ${{ inputs.directory }}
      run: |
        ls rpm/*.rpm 2>/dev/null | head -1 | grep -q . || exit 0
        sudo apt-get install -y createrepo-c
        [ ${{ inputs.mode }} = append ] && createrepo_c --update rpm || createrepo_c rpm
